<?xml version="1.0"?>
<package format="3">
  <name>robot_arm_bringup</name>
  <version>0.0.1</version>
  <description>ROS2 bringup nodes for the AX-12A robot arm.</description>
  <maintainer email="todo@example.com">BOMIN</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>

  <exec_depend>python3</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>

